# Site settings
title: 
header-img: img/home-bg.png
email: ayesha.x.ansari@gmail.com
copyright_name: ayesha-x-ansari
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ayesha-x-ansari
learn_profile: ayesha-x-ansari
email_username: ayesha.x.ansari@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
